apiVersion: v1
kind: ConfigMap
metadata:
  name: react-config
data:
  REACT_APP_BASE_URL: "https://api.tamam123.com"
  REACT_APP_TAP_PUB_KEY: "pk_test_qDdOx6ufrkJiNc5lo9nHM0zT"
  REACT_APP_TAP_MERCHANT_ID: "24197412"
